### ISSUE TITLE
Feature Request - Integration with OmniHopper

### ISSUE THREAD

**Issue by stinkysmellystinkysmelly** [QPCrummer/Hopper-Speed-Simulator#1]
Hi I was wondering if it would be possible to add compatibility with OmniHopper (https://github.com/enjarai/OmniHopper)

OmniHopper allows hoppers to be placed in any orientation (i.e. upside-down)

It would be really great if modifying speeds with Hopper Speed Simulator also modified the speed of OmniHoppers

**Comment by QPCrummer** [comment]
@Bobder I could definitely add compat with Omni hopper. Seems as simple as just changing a few numbers in the code. I’ll see when I can get time to complete your request.

**Comment by QPCrummer** [comment]
Sorry about this, but for the time being I'll have to put this on hold. Gradle is being annoying and not letting me add Omnihopper as a dependency. Sorry for the inconvenience.

**Comment by QPCrummer** [comment]
Closing this as omnihopper appears to not be updating anymore
