### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by PDamion** [QPCrummer/Hopper-Speed-Simulator#2]
"ticks-per-item" works 1.19.2 but "items-per-transfer" does not. Could this possibly be updated to 1.19.2?

**Comment by QPCrummer** [comment]
I'm not sure I actually properly implemented in 1.18,2 either. I'll look into actually implementing it

**Comment by QPCrummer** [comment]
Actually, just tested it and it works just fine for me

**Comment by QPCrummer** [comment]
https://user-images.githubusercontent.com/66036033/197916228-ab1243df-e67b-4805-ab2c-4e58c8de2ce6.mp4

**Comment by QPCrummer** [comment]
Wait, I just found the issue. With the latest addition of hopper sleeping by Lithium, that actually breaks the multi-item transfers that my mod is doing. I'll have to see if I can sort that out, either by adding compat or disabling the optimization if I cannot fix it

For right now, in the lithium config type: mixin.block.hopper=false

**Comment by PDamion** [comment]
it's no rush trying to sort that out with the config-changing workaround. i appreciate the help!

**Comment by venaminecraft** [comment]
Hello @QPCrummer, any update on this?
I would love to use the benefits from Lithium, since I have a large storage hall.

**Comment by QPCrummer** [comment]
@sternschnaube I’ll take a look at this tomorrow. Lithium is still compatible, but you just have to disable lithium’s hopper sleeping. The current issue is that I try to send items faster than lithium’s hoppers can stop sleeping, which obviously will cause issues. I’ll see if there is some way to wake the hoppers more quickly and get this issue fixed.

**Comment by QPCrummer** [comment]
@sternschnaube 
The latest lithium dev build seems compatible with my mod except it may break the multiple items per transfer rule. Gradle is acting up, so I may have to push it off for a few days till I can get that fixed.

**Comment by venaminecraft** [comment]
Thanks already 😊

**Comment by QPCrummer** [comment]
Multiple item transfer has now been fixed when lithium is installed as of version 1.3.0.
