### ISSUE TITLE
Can be marked as 1.19.3 compatible

### ISSUE THREAD

**Issue by sternschnaube** [QPCrummer/Hopper-Speed-Simulator#4]
Hello, hopperspeed set to 4 was working.
I was disabling the Lithium mixin too, as you was recommending it in #2.

**Comment by QPCrummer** [comment]
@sternschnaube While the mod launches in 1.19.3, items-per-transfer doesn't work 
Sorry for such an extremely late response. I'm currently working on fixing it

This is an incompatibility with lithium, which I assume that basically everyone uses, so I'll fix that before I release a new version

**Comment by QPCrummer** [comment]
The incompatibility with Lithium has been fully resolved and all optimizations from lithium are preserved.
