### ISSUE TITLE
1.20.1 update?

### ISSUE THREAD

**Issue by Perfomance1** [QPCrummer/Hopper-Speed-Simulator#5]
are you gonna update this mod?its really useful

**Comment by QPCrummer** [comment]
@Perfomance1 
Here you go, I updated it to 1.20.1 https://modrinth.com/mod/hopperspeedsim/version/1.2.0

Just keep in mind that it is still not fully compatible with lithium. You need to put `mixin.block.hopper=false` in lithium's config
