### ISSUE TITLE
About Lithium

### ISSUE THREAD

**Issue by MaxenceDC** [QPCrummer/Hopper-Speed-Simulator#6]
You might be interested in reading this : https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json

**Comment by QPCrummer** [comment]
Added in the latest release, thank you for suggesting this!

https://modrinth.com/mod/hopperspeedsim/version/1.2.1
