### ISSUE TITLE
Config file resets on server start

### ISSUE THREAD

**Issue by C4ArtZ** [QPCrummer/Hopper-Speed-Simulator#7]
Hi,

thank you for writing this mod!

I would like to have the set speed persist after a restart. 
I saw that your mod adds a config file, so I tried setting the desired values in there.

These values get reset back to default whenever the server starts.

Do you think you could make the config persistant?

**Comment by QPCrummer** [comment]
I can absolutely fix this issue. I’ll have it fixed and a new version released today.

**Comment by QPCrummer** [comment]
Sorry about the delay on this. I may or may not have forgotten about this. It has now been fixed in version 1.3.0
