### ISSUE TITLE
1.20.6 dosent work with this mod

### ISSUE THREAD

**Issue by DJGuu12** [QPCrummer/Hopper-Speed-Simulator#8]
when i install the mod on modrinth and launch the game, it always crashed idk why, is anyone having this issue?

**Comment by QPCrummer** [comment]
Hello. Are you able to provide a log or crash report when the game crashes? You can either upload the file here, or copy and paste it on a site like mclo.gs. It will help a lot when trying to diagnose an issue.

**Comment by DJGuu12** [comment]
sure, let me just install the mod again

**Comment by DJGuu12** [comment]
https://mclo.gs/E1ASb1D

**Comment by DJGuu12** [comment]
ive already asked the fabric discord server player help and someone told me to "uninstall it and report it to their github"

**Comment by QPCrummer** [comment]
Thank you. Yeah that’s a good recommendation from the Fabric discord. I’ll try to have it fixed later today if I have time.

**Comment by QPCrummer** [comment]
@DJGuu12 This version should fix that crash as well as adding full support for Omnihopper. Turns out Omnihopper removes all of Lithium's hopper optimizations, so that broke my code that depended on Lithium's. 

https://modrinth.com/mod/hopperspeedsim/version/1.3.2

**Comment by DJGuu12** [comment]
Ok, thanks!
