### ISSUE TITLE
MC crash at launch

### ISSUE THREAD

**Issue by averion0** [QPCrummer/Hopper-Speed-Simulator#9]
Getting "Error Code #1" with this mod, please fix

**Comment by Ampflower** [comment]
Send a crash report and/or logs. Exit codes are meaningless on their own.
~~Frankly wish the vanilla launcher never went showing only an unhelpful exit code, but oh well.~~

**Comment by averion0** [comment]
[crash-2024-07-20_07.51.00-client.txt](https://github.com/user-attachments/files/16337637/crash-2024-07-20_07.51.00-client.txt)
i think its this one

**Comment by QPCrummer** [comment]
That is not my mod crashing. It is a mod called "veindigging"

**Comment by averion0** [comment]
[crash-2024-07-20_00.29.45-client.txt](https://github.com/user-attachments/files/16337661/crash-2024-07-20_00.29.45-client.txt)
what about this one?

**Comment by QPCrummer** [comment]
Nope, that is a Continuity issue

**Comment by averion0** [comment]
lemme try this mod again and send the log if it crashes

**Comment by QPCrummer** [comment]
You don't even have my mod installed in these crash reports

**Comment by averion0** [comment]
they're the only logs i have

**Comment by averion0** [comment]
[latest.log](https://github.com/user-attachments/files/16337681/latest.log)
here, just put the .jar in my mods folder and launched the game (btw omnihopper is installed)

**Comment by QPCrummer** [comment]
It's probably not compatible with the latest version of omnihopper since that mod was late to updating to 1.21. I just kept my original compatibility code since a newer omnihopper didn't exist

**Comment by QPCrummer** [comment]
Closing this as omnihopper appears to not be updating anymore
